### ISSUE TITLE
Can't enable multi-selection in the issues

### ISSUE THREAD

**Issue by benoitlm** [akabekobeko/redmine-theme-minimalflat#1]
Hi,

Action to select all issues not working (see attachment). Can you check what's wrong?

Thanks in advance.

Regards,

![pb](https://cloud.githubusercontent.com/assets/5756348/9882191/cddb1a80-5bd3-11e5-95b0-e428b8f73f31.png)

**Comment by akabekobeko** [comment]
Thank you for the report.

This project has stopped the development, But we're going to fix because there was a report.
By the way, the next of this project will be [akabekobeko/redmine-theme-minimalflat2](https://github.com/akabekobeko/redmine-theme-minimalflat2).

**Comment by benoitlm** [comment]
Thanks ;-)

**Comment by akabekobeko** [comment]
Fixed this bug, Please wait because it is reflected in the next release.

![ss-01](https://cloud.githubusercontent.com/assets/1257526/9907670/38396754-5ccb-11e5-98b4-240e679ca8a5.png)
